/**
 * AppexQuant Markets Global - Leaderboard & Hall of Fame Mock / Seed Data Service
 * Implements 2-Year Rolling Retention (24 Months), Real-time Performance Tracking & Badges
 */

import { LeaderboardEntry, HallOfFameInductee, VerifiedBadge, MonthlyRecord, LeaderboardWindow } from '../../types/leaderboard.ts';

// Verified Badges Definition
export const BADGE_TRIPLE_LEADER_PURPLE: VerifiedBadge = {
  type: 'TRIPLE_LEADER_PURPLE',
  label: 'Triple Leader 3x',
  description: 'Achieved 3x #1 First-Place Leaderboard Victories across audited competition cycles.',
  iconType: 'crown',
  badgeColor: 'bg-purple-600/20 text-purple-400 border-purple-500/40 shadow-purple-500/20',
  glowColor: '#a855f7',
  grantedAt: '2025-11-30',
};

export const BADGE_ALL_TIME_EARNER_GOLD: VerifiedBadge = {
  type: 'ALL_TIME_EARNER_GOLD',
  label: 'All-Time Top Earner ✔️',
  description: 'Reigning #1 All-Time Audited Profit Earner on AppexQuant Global Markets.',
  iconType: 'check-circle',
  badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-400/50 shadow-amber-500/30',
  glowColor: '#f59e0b',
  grantedAt: '2026-01-01',
};

export const BADGE_INSTITUTIONAL_CYAN: VerifiedBadge = {
  type: 'INSTITUTIONAL_CYAN',
  label: 'Institutional Tier',
  description: 'Direct DMA / Deriv Real Broker Telemetry Audited Stream.',
  iconType: 'shield-check',
  badgeColor: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/40 shadow-cyan-500/20',
  glowColor: '#06b6d4',
  grantedAt: '2025-06-15',
};

export const BADGE_ALGO_MASTER_EMERALD: VerifiedBadge = {
  type: 'ALGO_MASTER_EMERALD',
  label: 'Algo Vanguard',
  description: 'Over 2,500+ Automated EA Execution passes with sub-second execution.',
  iconType: 'sparkles',
  badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40 shadow-emerald-500/20',
  glowColor: '#10b981',
  grantedAt: '2025-08-10',
};

// Generate 24-Month Rolling Performance Retention Logs (Aug 2024 - Aug 2026)
function generate2YearLogs(baseMonthlyPnl: number, winRate: number): MonthlyRecord[] {
  const records: MonthlyRecord[] = [];
  const startYear = 2024;
  const startMonth = 8; // Aug 2024

  for (let i = 0; i < 24; i++) {
    const totalMonths = startMonth + i;
    const year = startYear + Math.floor((totalMonths - 1) / 12);
    const monthNum = ((totalMonths - 1) % 12) + 1;
    const monthStr = `${year}-${monthNum.toString().padStart(2, '0')}`;

    // Variance in monthly pnl
    const variance = 0.8 + Math.sin(i * 0.7) * 0.4 + (i % 3) * 0.1;
    const pnl = Math.round(baseMonthlyPnl * variance);
    const trades = Math.round(40 + (i * 3) + Math.cos(i) * 15);
    const wr = Math.min(96, Math.max(58, +(winRate + (Math.sin(i) * 3.5)).toFixed(1)));
    const dd = +(2.1 + (Math.abs(Math.sin(i * 1.3)) * 4.2)).toFixed(1);

    records.push({
      month: monthStr,
      pnlUsd: pnl,
      winRatePct: wr,
      tradeCount: trades,
      maxDrawdownPct: dd,
      rankInWindow: Math.max(1, Math.min(10, Math.round(1 + Math.abs(Math.sin(i * 0.9) * 5)))),
    });
  }

  return records;
}

// Master Leaderboard Data with Rolling 2-Year Records & Badges
export const LEADERBOARD_MASTER_DATA: Record<LeaderboardWindow, LeaderboardEntry[]> = {
  WEEKLY: [
    {
      rank: 1,
      userId: 'usr-alex-001',
      displayName: 'Alex Nyangaresi Obwogi',
      username: 'alex_obwogi',
      avatar: 'AO',
      country: 'KE',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 48920.50,
      roiPct: 68.4,
      winRatePct: 88.6,
      profitFactor: 4.82,
      totalTrades: 114,
      maxDrawdownPct: 2.8,
      sharpeRatio: 3.42,
      streakWins: 14,
      primaryStrategy: 'Volatility Index 100 1s Scalper Pro + HFT Quant',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 4, // Eligible for Triple-Leader Purple Badge!
      isAllTimeLeader: true,     // Eligible for Gold All-Time Earner Badge!
      badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(38000, 88.6),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 2,
      userId: 'usr-elena-002',
      displayName: 'Elena Rostova',
      username: 'elena_quant',
      avatar: 'ER',
      country: 'CH',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 36410.00,
      roiPct: 51.2,
      winRatePct: 84.1,
      profitFactor: 3.95,
      totalTrades: 92,
      maxDrawdownPct: 3.4,
      sharpeRatio: 2.98,
      streakWins: 9,
      primaryStrategy: 'EUR/USD SMC Order Flow Sentinel',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 3, // Eligible for Triple-Leader Purple Badge!
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(29000, 84.1),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 3,
      userId: 'usr-marcus-003',
      displayName: 'Marcus Sterling',
      username: 'm_sterling',
      avatar: 'MS',
      country: 'UK',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 29840.20,
      roiPct: 44.7,
      winRatePct: 81.3,
      profitFactor: 3.45,
      totalTrades: 86,
      maxDrawdownPct: 4.1,
      sharpeRatio: 2.76,
      streakWins: 7,
      primaryStrategy: 'XAU/USD Gold Breakout Alpha Engine',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 3, // Triple Leader
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(24000, 81.3),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 4,
      userId: 'usr-kenji-004',
      displayName: 'Kenji Sato',
      username: 'kenji_tokyo',
      avatar: 'KS',
      country: 'JP',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 22150.00,
      roiPct: 38.9,
      winRatePct: 79.5,
      profitFactor: 3.12,
      totalTrades: 105,
      maxDrawdownPct: 4.6,
      sharpeRatio: 2.54,
      streakWins: 6,
      primaryStrategy: 'Synthetic Jump 75 Grid Optimizer',
      brokerFeed: 'Deriv Real WebSocket Feed #3',
      firstPlaceFinishesCount: 1,
      isAllTimeLeader: false,
      badges: [BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(18000, 79.5),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 5,
      userId: 'usr-sophia-005',
      displayName: 'Sophia Chen',
      username: 'sophia_alpha',
      avatar: 'SC',
      country: 'SG',
      accountType: 'PROP_VERIFIED',
      pnlUsd: 19480.00,
      roiPct: 32.5,
      winRatePct: 77.2,
      profitFactor: 2.89,
      totalTrades: 74,
      maxDrawdownPct: 3.9,
      sharpeRatio: 2.41,
      streakWins: 5,
      primaryStrategy: 'Crypto Momentum & BTC/USD Scalper',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 2,
      isAllTimeLeader: false,
      badges: [BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(16000, 77.2),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 6,
      userId: 'usr-david-006',
      displayName: 'David Vance',
      username: 'dvance_quant',
      avatar: 'DV',
      country: 'US',
      accountType: 'PRO_PAPER',
      pnlUsd: 15300.00,
      roiPct: 27.8,
      winRatePct: 74.5,
      profitFactor: 2.65,
      totalTrades: 62,
      maxDrawdownPct: 5.2,
      sharpeRatio: 2.15,
      streakWins: 4,
      primaryStrategy: 'Statistical Arbitrage & Mean Reversion',
      brokerFeed: 'Deriv Virtual Pro Sandbox',
      firstPlaceFinishesCount: 0,
      isAllTimeLeader: false,
      badges: [],
      historicalRetentionLogs: generate2YearLogs(12000, 74.5),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
  ],
  MONTHLY: [
    {
      rank: 1,
      userId: 'usr-alex-001',
      displayName: 'Alex Nyangaresi Obwogi',
      username: 'alex_obwogi',
      avatar: 'AO',
      country: 'KE',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 184500.00,
      roiPct: 215.4,
      winRatePct: 89.2,
      profitFactor: 5.12,
      totalTrades: 460,
      maxDrawdownPct: 3.1,
      sharpeRatio: 3.65,
      streakWins: 18,
      primaryStrategy: 'Synthetic Volatility Index Multi-Frame Alpha Engine',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 4,
      isAllTimeLeader: true,
      badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(38000, 89.2),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 2,
      userId: 'usr-elena-002',
      displayName: 'Elena Rostova',
      username: 'elena_quant',
      avatar: 'ER',
      country: 'CH',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 142800.00,
      roiPct: 178.6,
      winRatePct: 85.4,
      profitFactor: 4.18,
      totalTrades: 382,
      maxDrawdownPct: 3.8,
      sharpeRatio: 3.10,
      streakWins: 11,
      primaryStrategy: 'EUR/USD SMC Order Flow Sentinel',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 3,
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(29000, 85.4),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 3,
      userId: 'usr-marcus-003',
      displayName: 'Marcus Sterling',
      username: 'm_sterling',
      avatar: 'MS',
      country: 'UK',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 118600.00,
      roiPct: 154.2,
      winRatePct: 82.7,
      profitFactor: 3.68,
      totalTrades: 345,
      maxDrawdownPct: 4.5,
      sharpeRatio: 2.85,
      streakWins: 8,
      primaryStrategy: 'XAU/USD Gold Breakout Alpha Engine',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 3,
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(24000, 82.7),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 4,
      userId: 'usr-kenji-004',
      displayName: 'Kenji Sato',
      username: 'kenji_tokyo',
      avatar: 'KS',
      country: 'JP',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 89400.00,
      roiPct: 118.5,
      winRatePct: 80.1,
      profitFactor: 3.25,
      totalTrades: 410,
      maxDrawdownPct: 4.9,
      sharpeRatio: 2.62,
      streakWins: 7,
      primaryStrategy: 'Synthetic Jump 75 Grid Optimizer',
      brokerFeed: 'Deriv Real WebSocket Feed #3',
      firstPlaceFinishesCount: 1,
      isAllTimeLeader: false,
      badges: [BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(18000, 80.1),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 5,
      userId: 'usr-sophia-005',
      displayName: 'Sophia Chen',
      username: 'sophia_alpha',
      avatar: 'SC',
      country: 'SG',
      accountType: 'PROP_VERIFIED',
      pnlUsd: 76200.00,
      roiPct: 98.4,
      winRatePct: 78.4,
      profitFactor: 3.02,
      totalTrades: 298,
      maxDrawdownPct: 4.2,
      sharpeRatio: 2.48,
      streakWins: 6,
      primaryStrategy: 'Crypto Momentum & BTC/USD Scalper',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 2,
      isAllTimeLeader: false,
      badges: [BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(16000, 78.4),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
  ],
  YEARLY: [
    {
      rank: 1,
      userId: 'usr-alex-001',
      displayName: 'Alex Nyangaresi Obwogi',
      username: 'alex_obwogi',
      avatar: 'AO',
      country: 'KE',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 1420800.00,
      roiPct: 620.5,
      winRatePct: 91.4,
      profitFactor: 5.84,
      totalTrades: 4280,
      maxDrawdownPct: 3.6,
      sharpeRatio: 4.12,
      streakWins: 24,
      primaryStrategy: 'AppexQuant Sovereign Alpha Suite (Vol 100 1s / XAU / FX)',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 4,
      isAllTimeLeader: true,
      badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(38000, 91.4),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 2,
      userId: 'usr-elena-002',
      displayName: 'Elena Rostova',
      username: 'elena_quant',
      avatar: 'ER',
      country: 'CH',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 980400.00,
      roiPct: 445.8,
      winRatePct: 86.8,
      profitFactor: 4.45,
      totalTrades: 3640,
      maxDrawdownPct: 4.2,
      sharpeRatio: 3.48,
      streakWins: 14,
      primaryStrategy: 'EUR/USD SMC Institutional Liquidity Hunter',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 3,
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(29000, 86.8),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 3,
      userId: 'usr-marcus-003',
      displayName: 'Marcus Sterling',
      username: 'm_sterling',
      avatar: 'MS',
      country: 'UK',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 842000.00,
      roiPct: 392.1,
      winRatePct: 83.9,
      profitFactor: 3.92,
      totalTrades: 3120,
      maxDrawdownPct: 4.8,
      sharpeRatio: 3.12,
      streakWins: 10,
      primaryStrategy: 'Gold Precision Momentum EA',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 3,
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(24000, 83.9),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 4,
      userId: 'usr-kenji-004',
      displayName: 'Kenji Sato',
      username: 'kenji_tokyo',
      avatar: 'KS',
      country: 'JP',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 615000.00,
      roiPct: 290.4,
      winRatePct: 81.2,
      profitFactor: 3.42,
      totalTrades: 3890,
      maxDrawdownPct: 5.4,
      sharpeRatio: 2.84,
      streakWins: 8,
      primaryStrategy: 'Synthetic Jump 75 Grid Optimizer',
      brokerFeed: 'Deriv Real WebSocket Feed #3',
      firstPlaceFinishesCount: 1,
      isAllTimeLeader: false,
      badges: [BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(18000, 81.2),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
  ],
  ALL_TIME: [
    {
      rank: 1,
      userId: 'usr-alex-001',
      displayName: 'Alex Nyangaresi Obwogi',
      username: 'alex_obwogi',
      avatar: 'AO',
      country: 'KE',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 2840500.00,
      roiPct: 1240.8,
      winRatePct: 92.1,
      profitFactor: 6.24,
      totalTrades: 8940,
      maxDrawdownPct: 3.6,
      sharpeRatio: 4.38,
      streakWins: 24,
      primaryStrategy: 'AppexQuant Sovereign Alpha Suite (Vol 100 1s / XAU / FX)',
      brokerFeed: 'Deriv Real MT5 Server #1 (Audited)',
      firstPlaceFinishesCount: 4,
      isAllTimeLeader: true,
      badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN, BADGE_ALGO_MASTER_EMERALD],
      historicalRetentionLogs: generate2YearLogs(38000, 92.1),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
    {
      rank: 2,
      userId: 'usr-elena-002',
      displayName: 'Elena Rostova',
      username: 'elena_quant',
      avatar: 'ER',
      country: 'CH',
      accountType: 'LIVE_DERIV_AUDITED',
      pnlUsd: 1950000.00,
      roiPct: 880.4,
      winRatePct: 87.5,
      profitFactor: 4.82,
      totalTrades: 7200,
      maxDrawdownPct: 4.2,
      sharpeRatio: 3.72,
      streakWins: 14,
      primaryStrategy: 'EUR/USD SMC Institutional Liquidity Hunter',
      brokerFeed: 'Deriv Real MT5 Server #2 (Audited)',
      firstPlaceFinishesCount: 3,
      isAllTimeLeader: false,
      badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
      historicalRetentionLogs: generate2YearLogs(29000, 87.5),
      lastUpdated: 'Live Streaming (Real-Time)',
    },
  ],
};

// Permanent Hall of Fame Inductees with Verified Thumbnails & Audit Telemetry
export const HALL_OF_FAME_INDUCTEES: HallOfFameInductee[] = [
  {
    id: 'hof-2025-alex',
    userId: 'usr-alex-001',
    displayName: 'Alex Nyangaresi Obwogi',
    username: 'alex_obwogi',
    avatar: 'AO',
    country: 'KE',
    inductionTitle: 'All-Time Sovereign Grandmaster & 2025 Yearly Champion',
    inductionPeriod: 'Year 2025 & All-Time Audited Record',
    inductionWindow: 'YEARLY',
    totalPnlCapturedUsd: 1420800.00,
    roiCapturedPct: 620.5,
    winRatePct: 91.4,
    totalVerifiedTrades: 4280,
    profitFactor: 5.84,
    maxDrawdownPct: 3.6,
    inducteeQuote: 'Systematic discipline, sub-second latency via Deriv WebSocket APIs, and non-negotiable risk safeguards beat market randomness every single time.',
    verifiedTelemetryThumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
    badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
    inductedAt: '2025-12-31T23:59:59Z',
    auditVerificationHash: '0x8f2d9c44b7a1e3518a20d4f923b610c71a39f6048d21b3ce90a1876541f5a9e2',
  },
  {
    id: 'hof-2025-elena',
    userId: 'usr-elena-002',
    displayName: 'Elena Rostova',
    username: 'elena_quant',
    avatar: 'ER',
    country: 'CH',
    inductionTitle: '2025 Yearly Triple-Leader Laureate (SMC Order Flow)',
    inductionPeriod: 'Year 2025 Champion Runner-Up',
    inductionWindow: 'YEARLY',
    totalPnlCapturedUsd: 980400.00,
    roiCapturedPct: 445.8,
    winRatePct: 86.8,
    totalVerifiedTrades: 3640,
    profitFactor: 4.45,
    maxDrawdownPct: 4.2,
    inducteeQuote: 'Liquidity sweep recognition algorithms combined with automated risk brackets unlock exponential compounding.',
    verifiedTelemetryThumbnail: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80',
    badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_INSTITUTIONAL_CYAN],
    inductedAt: '2025-12-31T23:59:59Z',
    auditVerificationHash: '0x3a4b7c89d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7',
  },
  {
    id: 'hof-2024-marcus',
    userId: 'usr-marcus-003',
    displayName: 'Marcus Sterling',
    username: 'm_sterling',
    avatar: 'MS',
    country: 'UK',
    inductionTitle: '2024 Yearly Triple-Leader Inductee (Gold Breakout Alpha)',
    inductionPeriod: 'Year 2024 Grand Champion',
    inductionWindow: 'YEARLY',
    totalPnlCapturedUsd: 789500.00,
    roiCapturedPct: 382.4,
    winRatePct: 84.6,
    totalVerifiedTrades: 2950,
    profitFactor: 4.10,
    maxDrawdownPct: 4.5,
    inducteeQuote: 'When precision algorithms align with multi-timeframe volume imbalances, high win-rates become consistent realities.',
    verifiedTelemetryThumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
    badges: [BADGE_TRIPLE_LEADER_PURPLE, BADGE_ALGO_MASTER_EMERALD],
    inductedAt: '2024-12-31T23:59:59Z',
    auditVerificationHash: '0x9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b',
  },
  {
    id: 'hof-2025-07-alex',
    userId: 'usr-alex-001',
    displayName: 'Alex Nyangaresi Obwogi',
    username: 'alex_obwogi',
    avatar: 'AO',
    country: 'KE',
    inductionTitle: 'July 2025 #1 Sovereign Month Champion',
    inductionPeriod: 'Month of July 2025',
    inductionWindow: 'MONTHLY',
    totalPnlCapturedUsd: 196400.00,
    roiCapturedPct: 232.0,
    winRatePct: 93.5,
    totalVerifiedTrades: 512,
    profitFactor: 6.10,
    maxDrawdownPct: 2.4,
    inducteeQuote: 'Peak market synchronization achieved across Synthetic Volatility 100 1s cycles.',
    verifiedTelemetryThumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    badges: [BADGE_ALL_TIME_EARNER_GOLD, BADGE_TRIPLE_LEADER_PURPLE],
    inductedAt: '2025-07-31T23:59:59Z',
    auditVerificationHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
  },
];
