/**
 * AppexQuant Markets Global - EA Hub & Ecosystem Service
 * Provides verified Expert Advisors (EAs), licensing rights, installation workflow, and performance records.
 */

import { ExpertAdvisor, SuccessStory, DailyPerformanceRecord, EASubmissionPayload } from '../../types/ea.ts';

export const INITIAL_EXPERT_ADVISORS: ExpertAdvisor[] = [
  {
    id: 'ea-01',
    name: 'Apex Scalper Pro MT5',
    tagline: 'High-frequency institutional order block scalper optimized for EUR/USD & GBP/USD.',
    description: 'Designed exclusively for Deriv MT5 accounts. Captures 5 to 15 pip liquidity sweeps during London and New York open sessions with strict 1:2.5 risk-reward enforcement.',
    category: 'SCALPING',
    developer: 'QuantEdge Labs',
    owner: 'AppexQuant Verified Partner',
    license: 'FREE_FOREVER',
    isFreeForever: true,
    version: '2.4.1',
    sourceType: 'IN_HOUSE',
    fileType: 'COMPILED_ONLY',
    fileSizeKb: 342,
    checksum: 'sha256-8f4b9a2c3d1e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c',
    redistributionPermission: true,
    modificationPermission: false,
    commercialPermission: true,
    terms: '100% Free Forever under AppexQuant Permissive Community License. No hidden subscriptions.',
    publishedDate: '2026-01-15',
    lastUpdated: '2026-07-20',
    supportedPlatform: 'MetaTrader 5',
    broker: 'Deriv MT5',
    supportedSymbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'AUDUSD'],
    recommendedTimeframes: ['M5', 'M15'],
    riskProfile: 'Moderate',
    performance: {
      netProfitUsd: 14250.80,
      grossProfitUsd: 22400.50,
      grossLossUsd: -8149.70,
      winRatePct: 68.4,
      lossRatePct: 31.6,
      profitFactor: 2.75,
      maxDrawdownPct: 6.2,
      totalTrades: 420,
      averageWinUsd: 78.20,
      averageLossUsd: -61.40,
      expectancyUsd: 33.93,
      sharpeRatio: 2.34,
      sortinoRatio: 2.89,
      recoveryFactor: 4.58,
      largestWinUsd: 340.00,
      largestLossUsd: -150.00,
    },
    datasetInfo: {
      type: 'FORWARD_TEST',
      period: 'Jan 2026 - Aug 2026 (8 Months)',
      symbol: 'EURUSD',
      timeframe: 'M5',
      initialBalance: 10000,
      commissionAssumption: '$3.50 / lot',
      spreadAssumption: 'Variable (Avg 0.2 pips)',
      slippageAssumption: 'Historical Tick Slippage Modeled',
      dataSource: 'Deriv MT5 Institutional Feed',
      sampleSize: 420,
    },
    status: 'ONLINE',
    isInstalled: true,
    isFavorite: true,
    installedVersion: '2.4.1',
  },
  {
    id: 'ea-02',
    name: 'SMC Liquidity Matrix MT5',
    tagline: 'Smart Money Concept (SMC) break-of-structure and imbalance retest engine.',
    description: 'Identifies institutional order blocks, mitigation blocks, and Fair Value Gaps (FVG) across multi-timeframe charts.',
    category: 'SMC',
    developer: 'Institutional Quant Group',
    owner: 'Open Source Community',
    license: 'OPEN_SOURCE',
    isFreeForever: true,
    version: '1.8.0',
    sourceType: 'OPEN_SOURCE',
    fileType: 'SOURCE_AVAILABLE',
    fileSizeKb: 184,
    checksum: 'sha256-1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    redistributionPermission: true,
    modificationPermission: true,
    commercialPermission: true,
    terms: 'MIT Open Source License. Free to use, modify, and distribute.',
    publishedDate: '2025-11-10',
    lastUpdated: '2026-06-15',
    supportedPlatform: 'MetaTrader 5',
    broker: 'Deriv MT5',
    supportedSymbols: ['EURUSD', 'GBPUSD', 'XAUUSD', 'USDJPY'],
    recommendedTimeframes: ['H1', 'H4'],
    riskProfile: 'Conservative',
    performance: {
      netProfitUsd: 9840.20,
      grossProfitUsd: 15600.00,
      grossLossUsd: -5759.80,
      winRatePct: 62.1,
      lossRatePct: 37.9,
      profitFactor: 2.71,
      maxDrawdownPct: 4.8,
      totalTrades: 195,
      averageWinUsd: 128.50,
      averageLossUsd: -77.80,
      expectancyUsd: 50.46,
      sharpeRatio: 2.12,
      sortinoRatio: 2.54,
      recoveryFactor: 5.12,
      largestWinUsd: 520.00,
      largestLossUsd: -210.00,
    },
    datasetInfo: {
      type: 'BACKTEST',
      period: '2025 Full Year (12 Months OOS)',
      symbol: 'XAUUSD',
      timeframe: 'H1',
      initialBalance: 10000,
      commissionAssumption: '$4.00 / lot',
      spreadAssumption: 'Variable (Avg 1.2 pips)',
      slippageAssumption: 'Conservative 1 pip slippage',
      dataSource: 'Deriv Synthetic & Forex Historical Tick Data',
      sampleSize: 195,
    },
    status: 'ONLINE',
    isInstalled: false,
    isFavorite: true,
  },
  {
    id: 'ea-03',
    name: 'Trend Surfer Momentum MT5',
    tagline: 'Multi-timeframe moving average ribbon alignment and momentum continuation bot.',
    description: 'Rides sustained macroeconomic trends across Forex majors and commodities with trailing ATR stops.',
    category: 'TREND_FOLLOWING',
    developer: 'AlphaTrend Systems',
    owner: 'Verified Partner',
    license: 'FREE_FOREVER',
    isFreeForever: true,
    version: '3.1.2',
    sourceType: 'PARTNER',
    fileType: 'COMPILED_ONLY',
    fileSizeKb: 410,
    checksum: 'sha256-9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d',
    redistributionPermission: true,
    modificationPermission: false,
    commercialPermission: true,
    terms: 'Free Forever under AppexQuant Partner distribution agreement.',
    publishedDate: '2026-03-01',
    lastUpdated: '2026-08-01',
    supportedPlatform: 'MetaTrader 5',
    broker: 'Deriv MT5',
    supportedSymbols: ['EURUSD', 'GBPUSD', 'USDJPY', 'NZDUSD'],
    recommendedTimeframes: ['H1', 'H4'],
    riskProfile: 'Conservative',
    performance: {
      netProfitUsd: 18920.00,
      grossProfitUsd: 29500.00,
      grossLossUsd: -10580.00,
      winRatePct: 54.8,
      lossRatePct: 45.2,
      profitFactor: 2.79,
      maxDrawdownPct: 8.5,
      totalTrades: 310,
      averageWinUsd: 174.19,
      averageLossUsd: -76.40,
      expectancyUsd: 61.03,
      sharpeRatio: 1.98,
      sortinoRatio: 2.31,
      recoveryFactor: 3.82,
      largestWinUsd: 890.00,
      largestLossUsd: -250.00,
    },
    datasetInfo: {
      type: 'LIVE',
      period: 'Live Forward Testing (6 Months)',
      symbol: 'GBPUSD',
      timeframe: 'H1',
      initialBalance: 25000,
      commissionAssumption: '$3.00 / lot',
      spreadAssumption: 'Fixed Spread Simulation',
      slippageAssumption: 'Minimal Live Slippage',
      dataSource: 'Deriv MT5 Live Server',
      sampleSize: 310,
    },
    status: 'ONLINE',
    isInstalled: true,
    isFavorite: false,
    installedVersion: '3.1.2',
  },
  {
    id: 'ea-04',
    name: 'Breakout Volatility Squeeze MT5',
    tagline: 'Bollinger Band & Keltner Channel squeeze breakout sniper.',
    description: 'Detects periods of extreme market compression and places bracket orders to capture aggressive volatility expansion.',
    category: 'BREAKOUT',
    developer: 'Volatility Lab',
    owner: 'AppexQuant Verified Partner',
    license: 'FREE_FOREVER',
    isFreeForever: true,
    version: '1.2.5',
    sourceType: 'IN_HOUSE',
    fileType: 'COMPILED_ONLY',
    fileSizeKb: 215,
    checksum: 'sha256-554433221100ffeeeeddccbbaa99887766543210',
    redistributionPermission: true,
    modificationPermission: false,
    commercialPermission: true,
    terms: '100% Free Forever. No activations required.',
    publishedDate: '2026-05-10',
    lastUpdated: '2026-07-15',
    supportedPlatform: 'MetaTrader 5',
    broker: 'Deriv MT5',
    supportedSymbols: ['EURUSD', 'USDJPY', 'XAUUSD'],
    recommendedTimeframes: ['M15', 'H1'],
    riskProfile: 'Aggressive',
    performance: {
      netProfitUsd: 7450.00,
      grossProfitUsd: 14200.00,
      grossLossUsd: -6750.00,
      winRatePct: 48.5,
      lossRatePct: 51.5,
      profitFactor: 2.10,
      maxDrawdownPct: 11.4,
      totalTrades: 140,
      averageWinUsd: 202.06,
      averageLossUsd: -93.69,
      expectancyUsd: 53.21,
      sharpeRatio: 1.75,
      sortinoRatio: 1.95,
      recoveryFactor: 2.45,
      largestWinUsd: 950.00,
      largestLossUsd: -300.00,
    },
    datasetInfo: {
      type: 'BACKTEST',
      period: 'H1 2026 Backtest',
      symbol: 'XAUUSD',
      timeframe: 'M15',
      initialBalance: 10000,
      commissionAssumption: '$5.00 / lot',
      spreadAssumption: '1.5 pips',
      slippageAssumption: 'Standard',
      dataSource: 'Deriv Historical Tick Feed',
      sampleSize: 140,
    },
    status: 'OFFLINE',
    isInstalled: false,
    isFavorite: false,
  },
];

export const INITIAL_SUCCESS_STORIES: SuccessStory[] = [
  {
    id: 'story-01',
    traderName: 'Marcus V.',
    displayMode: 'DISPLAY_NAME',
    country: 'United Kingdom',
    experienceYears: 4,
    markets: ['EUR/USD', 'GBP/USD'],
    strategyUsed: 'Institutional Liquidity Sweep & Structure Shift',
    timePeriod: '6 Months (Jan - Jul 2026)',
    startingBalance: 10000,
    endingBalance: 24250,
    netResultUsd: 14250,
    riskProfile: 'Moderate (1.0% risk per trade)',
    quote: 'AppexQuant gave me the quantitative discipline and risk guardrails I needed. Sticking strictly to the 1:2.5 R:R rule transformed my consistency.',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-07-25',
  },
  {
    id: 'story-02',
    traderName: 'Elena R.',
    displayMode: 'DISPLAY_NAME',
    country: 'Germany',
    experienceYears: 6,
    markets: ['Gold (XAU/USD)', 'EUR/USD'],
    strategyUsed: 'Smart Money Concept (SMC) & FVG Mitigation',
    timePeriod: '1 Year (2025 - 2026)',
    startingBalance: 25000,
    endingBalance: 58900,
    netResultUsd: 33900,
    riskProfile: 'Conservative (0.75% risk per trade)',
    quote: 'The AI strategy scanner and News Sentinel helped me completely avoid high-impact CPI whipsaws. Essential toolkit for professional retail traders.',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-06-12',
  },
  {
    id: 'story-03',
    traderName: 'Anonymous Trader',
    displayMode: 'ANONYMOUS',
    country: 'Singapore',
    experienceYears: 3,
    markets: ['Synthetic Indices (Volatility 75)', 'Forex'],
    strategyUsed: 'Apex Scalper Pro MT5',
    timePeriod: '3 Months',
    startingBalance: 5000,
    endingBalance: 11400,
    netResultUsd: 6400,
    riskProfile: 'Moderate',
    quote: 'The free MT5 EA hub is phenomenal. Deploying the Apex Scalper on Deriv MT5 with verified risk guardrails was seamless.',
    verificationStatus: 'VERIFIED',
    createdAt: '2026-08-01',
  },
];

export function getSampleDailyPerformance(): DailyPerformanceRecord[] {
  return [
    { date: '2026-08-01', netPl: 145.50, tradeCount: 4, status: 'POSITIVE' },
    { date: '2026-08-02', netPl: -42.00, tradeCount: 3, status: 'NEGATIVE' },
    { date: '2026-08-03', netPl: 210.80, tradeCount: 5, status: 'POSITIVE' },
    { date: '2026-08-04', netPl: 88.20, tradeCount: 2, status: 'POSITIVE' },
    { date: '2026-08-05', netPl: 0.00, tradeCount: 0, status: 'NEUTRAL' },
    { date: '2026-08-06', netPl: 312.40, tradeCount: 6, status: 'POSITIVE' },
    { date: '2026-08-07', netPl: -75.00, tradeCount: 3, status: 'NEGATIVE' },
    { date: '2026-08-08', netPl: 195.00, tradeCount: 4, status: 'POSITIVE' },
  ];
}
