import type { VercelRequest, VercelResponse } from '@vercel/node';

let cachedApp: any = null;
let initPromise: Promise<any> | null = null;

async function getAppInstance() {
  if (cachedApp) return cachedApp;
  if (initPromise) return initPromise;

  initPromise = (async () => {
    // Dynamically load the bundled server artifact generated by esbuild
    // @ts-ignore
    const serverBundle = await import('../dist/server.cjs');
    const createApp = serverBundle.createApp || serverBundle.default?.createApp;
    if (!createApp) {
      throw new Error('createApp function not found in dist/server.cjs bundle');
    }
    const app = await createApp();
    cachedApp = app;
    return app;
  })();

  return initPromise;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    const app = await getAppInstance();
    return app(req, res);
  } catch (err: any) {
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ error: 'Server initialization failed', detail: err?.message || String(err) }));
  }
}

