import type { VercelRequest, VercelResponse } from '@vercel/node';

let appPromise: any = null;

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (!appPromise) {
    // Dynamically load the bundled server artifact generated by esbuild
    // @ts-ignore
    const serverBundle = await import('../dist/server.cjs');
    const createApp = serverBundle.createApp || serverBundle.default?.createApp;
    if (!createApp) {
      throw new Error('createApp function not found in dist/server.cjs bundle');
    }
    appPromise = createApp();
  }
  const app = await appPromise;
  return app(req, res);
}

